import { compile } from "sass";
import { writeFileSync } from "fs";

function escapeTemplate(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
}

const compiled = compile("styles/main.scss", { style: "compressed" });
const escaped = escapeTemplate(compiled.css);

const source = `// AUTOGENERATED\n\nexport const styles = \`${escaped}\`;\n`;

writeFileSync("src/styles.ts", source);
